### ISSUE TITLE
Help on transform values

### ISSUE THREAD

**Issue by labsforge** [Agamnentzar/ag-psd#153]
Hi, I'm getting an error with my transform array.. at least that what photoshop complaints about.. I've tryed to change here and there but no luck, I really need your help to figure this out.

I have a page with photos that should be on a smart-layer with clipping to handle the photo crop. For simplicity and debugging, I created a page without any crop rotations, just a simple rect with a LinkedFile.

this is what it should generate:
![image](https://github.com/Agamnentzar/ag-psd/assets/50380743/50a425ef-b011-4412-ae72-10a6276dda35)

this is the psd without the linkedfiles prop:
```
{
  "width": 7086,
  "height": 3543,
  "channels": 3,
  "bitsPerChannel": 8,
  "colorMode": 3,
  "imageResources": {
    "gridAndGuidesInformation": {
      "guides": []
    },
    "resolutionInfo": {
      "horizontalResolution": 300,
      "horizontalResolutionUnit": "PPI",
      "widthUnit": "Inches",
      "verticalResolution": 300,
      "verticalResolutionUnit": "PPI",
      "heightUnit": "Inches"
    }
  },
  "children": [
    {
      "name": "Background",
      "canvas": {}
    },
    {
      "name": "Frame 1",
      "children": [
        {
          "name": "vmk9mbFbtU",
          "top": 207,
          "left": 2498.6130319148933,
          "canvas": {}
        },
        {
          "name": "014.jpg",
          "clipping": true,
          "placedLayer": {
            "id": "vmk9mbFbtU",
            "placed": "uYkBhmQAMz",
            "type": "raster",
            "transform": [
              2498.6130319148933,
              207,
              4587.386968085106,
              207,
              4587.386968085106,
              3336.0000000000005,
              2498.6130319148933,
              3336.0000000000005
            ],
            "width": 2088.773936170213,
            "height": 3129.0000000000005
          }
        }
      ]
    }
  ]
}
```

this is the error:
![image](https://github.com/Agamnentzar/ag-psd/assets/50380743/2f67d800-e156-48e3-ba22-8a6372d97e56)

this is the file (with linkedFiles):
[page-001.zip](https://github.com/Agamnentzar/ag-psd/files/12577518/page-001.zip)

Thank you for this awesome lib 🙏

**Comment by Agamnentzar** [comment]
Ok I also couldn't get it to work and after a lot of testing it turns out Photoshop requires the id to be in a format of `20953ddb-9391-11ec-b4f1-c15674f50bc4`, otherwise it doesn't work. Additionally it seems Photoshop has some issues when warp field is missing from placedLayer. I just released version `17.0.3` with additional error checks and automatic adding of warp field if it's not provided so try that version and it should work now.

That said, this library will not render the transformed image for you, so if your aim is to have PNG image at the end this will not help you and a better way is to just use node-canvas. If your aim is to have PSD file as an output then you can use this library but you'll also have to use node-canvas to generate bitmap for the layer, otherwise it will be empty when you open it in photoshop, until to start transforming it.

**Comment by labsforge** [comment]
That was fast! Thank you very much for your testing! 
I just want to export the psd to be opened on photoshop.

"Photoshop requires the id to be in a format of 20953ddb-9391-11ec-b4f1-c15674f50bc4"
Re: Is that some known standard?

"you'll also have to use node-canvas to generate bitmap for the layer, otherwise it will be empty when you open it in photoshop, until to start transforming it."
Re: Interesting.. The bitmap must match the size of the layer? or it could be just a low quality resize?

Thank you again 🙏

**Comment by Agamnentzar** [comment]
> Re: Is that some known standard?

It's a GUID, you can just generate any sequence of 8, 4, 4, 4, 12 of lowercase hex characters joined by dashes.

> Re: Interesting.. The bitmap must match the size of the layer? or it could be just a low quality resize?

It should be the original image transformed by your transform, layer canvas doesn't have to be the same size, if it has any padding you can specify layer.left and layer.top to specify the offset.

**Comment by labsforge** [comment]
Updated the lib and changed the ids:
```
{
  "width": 7086,
  "height": 3543,
  "channels": 3,
  "bitsPerChannel": 8,
  "colorMode": 3,
  "imageResources": {
    "gridAndGuidesInformation": {
      "guides": []
    },
    "resolutionInfo": {
      "horizontalResolution": 300,
      "horizontalResolutionUnit": "PPI",
      "widthUnit": "Inches",
      "verticalResolution": 300,
      "verticalResolutionUnit": "PPI",
      "heightUnit": "Inches"
    }
  },
  "children": [
    {
      "name": "Background",
      "canvas": {}
    },
    {
      "name": "Frame 1",
      "children": [
        {
          "name": "vmk9mbFbtU",
          "top": 207,
          "left": 2480.99335106383,
          "canvas": {},
          "effects": {
            "stroke": [
              {
                "enabled": true,
                "position": "inside",
                "size": {
                  "units": "Pixels",
                  "value": 53
                },
                "fillType": "color",
                "color": {
                  "r": 164,
                  "g": 221,
                  "b": 0
                },
                "opacity": 1
              }
            ]
          }
        },
        {
          "name": "014.jpg",
          "clipping": true,
          "placedLayer": {
            "id": "054ae3a0-6a36-408a-9c51-8f2a391b11d6",
            "placed": "ecdc794f-4afd-479f-a12e-5bec2530f80a",
            "type": "raster",
            "transform": [
              2533.99335106383,
              260,
              4552.006648936171,
              260,
              4552.006648936171,
              3283.0000000000005,
              2533.99335106383,
              3283.0000000000005
            ],
            "width": 2018.0132978723407,
            "height": 3023.0000000000005
          }
        }
      ]
    }
  ]
}
```

[page-001.zip](https://github.com/Agamnentzar/ag-psd/files/12580949/page-001.zip)

Still no luck :(

**Comment by Agamnentzar** [comment]
`placedLayer.width` and `placedLayer.height` should be the size of the original image

**Comment by labsforge** [comment]
That makes a lot of sense, but still not working 🤔
[page-001.zip](https://github.com/Agamnentzar/ag-psd/files/12580984/page-001.zip)

**Comment by Agamnentzar** [comment]
It doesn't open for you? It opened for me in Photoshop CS6

**Comment by labsforge** [comment]
I'm using Photoshop 24.7.0 because I'm using the adobe cloud subscription 😓

**Comment by Agamnentzar** [comment]
Ok I got latest photoshop version and it does indeed fail I'll investigate it tomorrow some more.

**Comment by labsforge** [comment]
Interestingly, if I remove the placed layer from children, I get a different error opening the file, and if I also remove the linked file then it opens ok! very weird the linkedfile thing.. i'm using fs.readFileSync directly on `linkedfile.data` 
![image](https://github.com/Agamnentzar/ag-psd/assets/50380743/8fe355ab-2ddf-45c5-8a4b-bd9d662d2bef)

**Comment by Agamnentzar** [comment]
For the test I set linkeFiles like this

```js
linkedFiles: [
	{
		id: '20953ddb-9391-11ec-b4f1-c15674f50bc4',
		name: 'canvas.png',
		data: fs.readFileSync(path.join('test', 'write', 'simple', 'canvas.png')),
	},
],
```

**Comment by Agamnentzar** [comment]
But yes, my test file also doesn't open in new Photoshop so I can reproduce the issue.

**Comment by Agamnentzar** [comment]
Published version `17.0.4` with fixed saving for newer versions of Photoshop

**Comment by labsforge** [comment]
Hi @Agamnentzar I think it didnt got published..
>No matching version found for ag-psd@17.0.4

**Comment by Agamnentzar** [comment]
Sorry, my bad, must have not confirmed it. It should be up now.

**Comment by labsforge** [comment]
It works! 😲 I'm so excited!! 🤩 you're a legend sir 😎
![image](https://github.com/Agamnentzar/ag-psd/assets/50380743/a789da7d-35fd-41f8-af82-38e8874c826f)
 I'll keep you updated on my progress 🙏 I'm going to generate the canvas for the placed layers

**Comment by labsforge** [comment]
OMG this is so awesome! I didn't expect this at 1st try! 👌
![image](https://github.com/Agamnentzar/ag-psd/assets/50380743/c6e3fdb9-46e4-4d1b-a7d1-ff65ce3a7411)


![image](https://github.com/Agamnentzar/ag-psd/assets/50380743/fd30eb01-14d0-431f-b1e4-8cbb2571b3f1)
